host: 0.0.0.0 # for Docker
title: VMII
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # subpath of your site, e.g. /blog
url: "https://www.vmii.org/blog"
twitter_username: vmii_org


collections:
  # Diátaxis framework https://diataxis.fr/
  concepts: # aka "explanations"
    output: true
    permalink: /docs/:collection/:name
    sort_by: order
  howtos:
    output: true
    permalink: /docs/:collection/:name
  tutorials:
    output: true
    permalink: /docs/:collection/:name
  references:
    permalink: /docs/:collection/:name
    output: true
  columns:
    output: false # handled by _references/columns
    sort_by: name