gems:
  - jekyll-liquify
  - jekyll-feed

feed:
  path: /assets-static/feed.xml

permalink: pretty # no :output_ext
host: 0.0.0.0 # for Docker
title: VMII
description: >-
  Learn about the Vocal Music Instrumentation Index, a project to index thousands of arias,
  duets, and choruses by instrumentation, text, and more.
baseurl: "" # subpath of your site, e.g. /blog
url: "https://www.vmii.org/"
twitter_username: vmii_org

exclude:
- 'README.md'
- Dockerfile

kramdown:
  syntax_highlighter: nil

collections:
  # Diátaxis framework https://diataxis.fr/
  basics: # aka "explanations"
    output: true
    permalink: /docs/:collection/:name
    sort_by: order
  howtos:
    output: true
    permalink: /docs/how-to/:name
  tutorials:
    output: true
    permalink: /docs/:collection/:name
  references:
    permalink: /docs/:collection/:name
    output: true
  columns:
    output: false # handled by _references/columns
    sort_by: name